project:
  type: website

website:
  title: "CAP 6938"
  google-analytics: "G-VCVVD4KWRF"
  search: false
  favicon: files/TheTab_KGrgb_square.png
  # Without this, the page footer will not display. It is removed in index.qmd
  navbar:
    background: dark

  page-footer:
    center:
      - text: \[Made with Quarto\]
        href: https://quarto.org
      - text: \[Source\]
        href: https://github.com/luqigroup/cap-6938
      - text: \[License\]
        href: https://raw.githubusercontent.com/luqigroup/cap-6938/refs/heads/main/LICENSE

format:
  html:
    css: styles.css
    theme:
      light: [simplex, custom.scss]
      dark: [cyborg, custom_dark.scss]
    fontsize: 1.0em
    linestretch: 1.4
    mainfont: "sans-serif"
    toc: true
    toc-title: "<br><br><br>"
    link-external-newwindow: false
    minimal: true
    grid:
      body-width: 1200px
